language: R
r: 
- current 
- devel
cache: packages
bioc_packages: 
- multtest
r_packages:
- reshape2
- GSA
- gtools
- cluster
- splines
- gplots
- stats
- graphics
- grDevices
- utils
- lme4
r_github_packages:
- hadley/ggplot2
- hadley/stringr
os:
- linux
- osx
r_build_args: "--html"
r_check_args: "--as-cran --timings"